name: Update flake.lock

on:
  schedule:
    # run every saturday
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  update:
    name: Run update
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Nix
        uses: NixOS/nix-installer-action@v1

      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@v29
        with:
          pr-title: 'nix: update flake.lock'

      - name: Enable Pull Request Automerge
        run: gh pr merge --rebase --auto "$PR_NUMBER"
        env:
          PR_NUMBER: ${{ steps.update.outputs.pull-request-number }}
          GH_TOKEN: ${{ secrets.AUTOMATA_TOKEN }}
